//! Provider-neutral domain model (architecture §5, §6, §9.3, §10.1).
//!
//! This module is Tauri-independent: no UI, no daemon wire types. Both the
//! daemon (structured agent API) and the GUI (snapshots/events) consume these
//! types, so a provider cannot smuggle its native shape past the boundary.
//! Every field here is the *general* rendering contract; provider-private data
//! may ride only inside `metadata` (`Option<serde_json::Value>`).

use serde::{Deserialize, Serialize};
use std::path::PathBuf;

// ── Provider capabilities (§5.1) ─────────────────────────────────

/// Static capability flags a provider reports after `initialize`/catalog.
/// UI features must be gated on these flags, never on a hardcoded provider id.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ProviderCapabilities {
    pub session_resume: bool,
    pub session_list: bool,
    pub structured_tools: bool,
    pub reasoning_stream: bool,
    pub permissions: bool,
    pub config_options: bool,
    pub slash_commands: bool,
    pub mcp_servers: bool,
    pub images: bool,
    pub context_usage: bool,
}

impl Default for ProviderCapabilities {
    fn default() -> Self {
        Self {
            session_resume: false,
            session_list: false,
            structured_tools: true,
            reasoning_stream: false,
            permissions: false,
            config_options: false,
            slash_commands: false,
            mcp_servers: false,
            images: false,
            context_usage: false,
        }
    }
}

// ── Provider catalog (§5.2) ─────────────────────────────────────

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ModelDefinition {
    pub id: String,
    pub label: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_window: Option<u64>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub reasoning_efforts: Vec<String>,
    #[serde(default)]
    pub is_default: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SelectOption {
    pub id: String,
    pub label: String,
}

/// A runtime-discovered configuration knob (model, mode, thinking, sandbox,
/// network, ...). The UI groups by `category`; nothing here is hardcoded per
/// provider.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ConfigOption {
    Select {
        id: String,
        label: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        category: Option<String>,
        current: String,
        options: Vec<SelectOption>,
    },
    Boolean {
        id: String,
        label: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        category: Option<String>,
        current: bool,
    },
}

impl ConfigOption {
    pub fn id(&self) -> &str {
        match self {
            ConfigOption::Select { id, .. } => id,
            ConfigOption::Boolean { id, .. } => id,
        }
    }
}

/// Value for setting a [`ConfigOption`].
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigValue {
    String(String),
    Bool(bool),
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ProviderCatalog {
    pub models: Vec<ModelDefinition>,
    #[serde(default)]
    pub config_options: Vec<ConfigOption>,
    pub capabilities: ProviderCapabilities,
}

/// Result of `diagnostic()`: is the binary present, authenticated, and what
/// version does it report?
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ProviderDiagnostic {
    pub available: bool,
    pub authenticated: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

/// One registered provider as exposed by `provider_list` (architecture §13).
/// `backend_kind` is `"acp"` | `"direct"` — the daemon is the authority on a
/// provider's backend type, so the frontend never hardcodes it when creating a
/// new agent (handoff §6 / §18.2).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ProviderInfo {
    pub provider_id: String,
    pub backend_kind: String,
}

// ── Prompt (§5.5) ───────────────────────────────────────────────

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum PromptContent {
    Text {
        text: String,
    },
    Image {
        mime_type: String,
        data: Vec<u8>,
    },
    Resource {
        uri: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        text: Option<String>,
    },
}

/// A user turn submission. `client_message_id` is generated by the manager at
/// submit time; the provider echo binds to the same canonical user item through
/// correlation metadata.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AgentPrompt {
    pub client_message_id: String,
    pub content: Vec<PromptContent>,
}

// ── Persistence handle (§10.1) ─────────────────────────────────

/// Provider-native pointer used to resume a session later. Never handed to a
/// different provider.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PersistenceHandle {
    pub provider_id: String,
    pub runtime_session_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native_handle: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

// ── Permissions (§9.3) ─────────────────────────────────────────

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PermissionKind {
    ToolCall,
    TerminalCommand,
    FileChange,
    ModeChange,
    Question,
    Other,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PermissionBehavior {
    Allow,
    Deny,
    Ask,
    Escalate,
}

/// What the permission is about — rendered as the request's subject line.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PermissionSubject {
    pub kind: PermissionKind,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PermissionAction {
    /// Provider-native action id — preserved verbatim, never collapsed into a
    /// bare allow/deny boolean.
    pub id: String,
    pub label: String,
    pub behavior: PermissionBehavior,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PermissionRequest {
    pub id: String,
    pub agent_id: String,
    pub kind: PermissionKind,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub subject: PermissionSubject,
    pub actions: Vec<PermissionAction>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PermissionResolution {
    pub request_id: String,
    pub action_id: String,
    pub resolved_at: i64,
}

// ── Context usage (§12.2) ───────────────────────────────────────

/// Current session context occupancy (optional capability). Account-level quota
/// is reported by the independent ProviderQuotaService, never here.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ContextUsage {
    pub context_window_used_tokens: Option<u64>,
    pub context_window_max_tokens: Option<u64>,
}

// ── Canonical timeline (§6.2) ───────────────────────────────────

pub type ItemId = String;
pub type TurnId = String;

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MessageRole {
    User,
    Assistant,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct MessageItem {
    pub item_id: ItemId,
    pub role: MessageRole,
    pub text: String,
    pub created_at: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolCallStatus {
    #[default]
    Pending,
    Running,
    Completed,
    Failed,
    Cancelled,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ToolCallItem {
    pub item_id: ItemId,
    pub tool_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_input: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_output: Option<serde_json::Value>,
    #[serde(default)]
    pub status: ToolCallStatus,
    pub created_at: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PlanItem {
    pub item_id: ItemId,
    pub title: String,
    pub content: String,
    pub created_at: i64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ErrorItem {
    pub item_id: ItemId,
    pub message: String,
    pub created_at: i64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", content = "data", rename_all = "snake_case")]
pub enum TimelineItem {
    UserMessage(MessageItem),
    AssistantMessage(MessageItem),
    Reasoning(MessageItem),
    ToolCall(ToolCallItem),
    Plan(PlanItem),
    Error(ErrorItem),
}

impl TimelineItem {
    /// Stable id used to stream updates to this item.
    pub fn item_id(&self) -> &str {
        match self {
            TimelineItem::UserMessage(m)
            | TimelineItem::AssistantMessage(m)
            | TimelineItem::Reasoning(m) => &m.item_id,
            TimelineItem::ToolCall(t) => &t.item_id,
            TimelineItem::Plan(p) => &p.item_id,
            TimelineItem::Error(e) => &e.item_id,
        }
    }
}

/// Terminal status of a timeline item (mostly tool calls; messages are complete
/// once their text stops appending).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ItemStatus {
    Pending,
    Complete,
    Failed,
    Cancelled,
}

/// A mutation to the canonical timeline. Streaming updates reuse the same
/// `item_id`; the UI upserts by id and never dedups by text.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum TimelineEvent {
    Started { item: TimelineItem },
    Appended { item_id: ItemId, text_delta: String },
    Replaced { item: TimelineItem },
    Finished { item_id: ItemId, status: ItemStatus },
}

// ── Agent events (§6.1) ─────────────────────────────────────────

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SessionReady {
    pub provider_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_session_id: Option<String>,
    pub capabilities: ProviderCapabilities,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persistence: Option<PersistenceHandle>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TurnStarted {
    pub turn_id: TurnId,
    pub client_message_id: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TurnCompleted {
    pub turn_id: TurnId,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TurnCancelled {
    pub turn_id: TurnId,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TurnFailed {
    pub turn_id: TurnId,
    pub message: String,
}

/// Every structured event a provider session can emit. `ContextUsageUpdated` is
/// an optional capability; account quota is never reported here (§12.3).
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "event", content = "data", rename_all = "snake_case")]
pub enum AgentEvent {
    SessionReady(SessionReady),
    TurnStarted(TurnStarted),
    Timeline(TimelineEvent),
    PermissionRequested(PermissionRequest),
    PermissionResolved(PermissionResolution),
    ConfigUpdated(Vec<ConfigOption>),
    ContextUsageUpdated(ContextUsage),
    TurnCompleted(TurnCompleted),
    TurnCancelled(TurnCancelled),
    TurnFailed(TurnFailed),
    SessionClosed,
}

// ── Unified lifecycle status (§6.3) ─────────────────────────────

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentStatus {
    /// Session created, still negotiating with the provider.
    Initializing,
    /// No foreground turn in flight.
    Idle,
    /// A foreground turn or explicit provider work event is active.
    Running,
    /// Blocked on an unresolved permission request.
    WaitingPermission,
    /// Blocked on a structured question/elicitation.
    WaitingInput,
    /// Terminal failure.
    Error,
    /// No live runtime (but the record may be resumable).
    Closed,
}

impl AgentStatus {
    pub fn is_live(&self) -> bool {
        matches!(
            self,
            AgentStatus::Initializing
                | AgentStatus::Idle
                | AgentStatus::Running
                | AgentStatus::WaitingPermission
                | AgentStatus::WaitingInput
        )
    }
}

// ── Session config ──────────────────────────────────────────────

/// The subset of agent settings a provider session needs at creation/resume.
/// Provider-independent; the provider maps these to its native protocol.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AgentSessionConfig {
    pub agent_id: String,
    pub cwd: PathBuf,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default)]
    pub config: Vec<(String, ConfigValue)>,
}

// ── Error model ─────────────────────────────────────────────────

#[derive(Debug, thiserror::Error)]
pub enum AgentError {
    #[error("provider not registered: {0}")]
    ProviderNotFound(String),
    #[error("provider not available: {0}")]
    ProviderNotAvailable(String),
    #[error("agent not found: {0}")]
    AgentNotFound(String),
    #[error("session already has a live runtime")]
    SessionAlreadyActive,
    #[error("session is closed")]
    SessionClosed,
    #[error("permission request not found: {0}")]
    PermissionRequestNotFound(String),
    #[error("permission request already resolved: {0}")]
    PermissionAlreadyResolved(String),
    #[error("adapter rejected an unsupported content type")]
    UnsupportedContent,
    #[error("provider error: {0}")]
    Provider(String),
    #[error("protocol error: {0}")]
    Protocol(String),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("invalid argument: {0}")]
    InvalidArgument(String),
}

impl AgentError {
    /// Stable machine code for the daemon protocol (no message parsing).
    pub fn code(&self) -> &'static str {
        match self {
            AgentError::ProviderNotFound(_) => "provider_not_found",
            AgentError::ProviderNotAvailable(_) => "provider_not_available",
            AgentError::AgentNotFound(_) => "agent_not_found",
            AgentError::SessionAlreadyActive => "session_already_active",
            AgentError::SessionClosed => "session_closed",
            AgentError::PermissionRequestNotFound(_) => "permission_not_found",
            AgentError::PermissionAlreadyResolved(_) => "permission_already_resolved",
            AgentError::UnsupportedContent => "unsupported_content",
            AgentError::Provider(_) => "provider_error",
            AgentError::Protocol(_) => "protocol_error",
            AgentError::Io(_) => "io_error",
            AgentError::InvalidArgument(_) => "invalid_argument",
        }
    }
}

/// Convenience helpers shared by manager + adapters.
pub(crate) fn now_ms() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}
